sudo: required
language: generic

service:
  - docker

before_install:
  - docker build -t nutcorp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nutcorp/react-test npm test

after_success:
  - docker build -t nutcorp/multi-client ./client
  - docker build -t nutcorp/multi-nginx ./nginx
  - docker build -t nutcorp/multi-server ./server
  - docker build -t nutcorp/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nutcorp/multi-client
  - docker push nutcorp/multi-nginx
  - docker push nutcorp/multi-server
  - docker push nutcorp/multi-worker
