sudo: required
service:
  - docker

before_install:
  - docker build -t mohexc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run monhexc/react-test npm test -- --coverage

after_success:
  - docker build -t mohexc/multi-client ./client
  - docker build -t mohexc/multi-nginx ./nginx
  - docker build -t mohexc/multi-server ./server
  - docker build -t mohexc/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mohexc/multi-client
  - docker push mohexc/multi-nginx
  - docker push mohexc/multi-server
  - docker push mohexc/multi-worker
